# Generated by Django 5.0.4 on 2024-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=120)),
                ('image_url', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
